---
- hosts: cloudera-prod 
  sudo: "yes"
  gather_facts: "no"
  remote_user: user
  tasks:
  - copy:
     src: "/home/user/scomsudoers3"
     dest: "/etc/sudoers.d/scomsudoers"
     owner: root
     group: root
     mode: 0644
