---
- hosts: cloudera 
  sudo: "yes"
  gather_facts: "no"
  remote_user: user
  tasks:
  - copy:
     src: "/home/user/cloudera"
     dest: "/etc/sudoers.d/cloudera"
     owner: root
     group: root
     mode: 0440
