---
- hosts: cloudera-prod 
  sudo: "yes"
  gather_facts: "no"
  remote_user: user
  tasks:
  - copy:
     src: "/home/user/vmware-tools.repo"
     dest: "/etc/yum.repos.d/vmware-tools.repo"
     owner: root
     group: root
     mode: 0644
