- hosts: misc 
  sudo: yes
  gather_facts: no 
  remote_user: ale00303
  tasks:
  - name: katello local sat setup
    get_url: 
      url: http://icisr400.echristus.net/pub/katello-ca-consumer-icisr400.echristus.net-1.0-1.noarch.rpm
      dest: /tmp/katello-ca-consumer-icisr400.echristus.net-1.0-1.noarch.rpm
      mode: 0440
