- hosts: misc 
  sudo: yes
  gather_facts: no 
  remote_user: user
  tasks:
  - name: katello local sat setup
    get_url: 
      url: http://$servername/pub/katello-ca-consumer-$servername-1.0-1.noarch.rpm
      dest: /tmp/katello-ca-consumer-$servername-1.0-1.noarch.rpm
      mode: 0440
