---
- hosts: database 
  sudo: yes
  gather_facts: no
  remote_user: ale00303
  tasks:
  - name: reboot nodes
    shell: sleep 2 && shutdown -r now "Ansible reboot"
    async: 1
    poll: 0
    ignore_errors: true

# - name: wait for server to come back
#      local_action: wait_for
#      args:
#        host: "{{ inventory_hostname }}"
#        port: 22
#        state: "started"
#	delay: 30
#        timeout: 300
