---
- name: "setup authorized_keys for the $user user" 
  hosts: all
  sudo: yes
  gather_facts: no
  remote_user: username
  tasks:
  - authorized_key: user=username  key="{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}" state=present
