---
- hosts: informatica-qa
  sudo: "yes"
  gather_facts: "no"
  remote_user: user
  tasks:
  - copy:
     src: "/home/user/ttu-foundation-1610.repo"
     dest: "/etc/yum.repos.d/ttu-foundation-1610.repo"
     owner: root
     group: root
     mode: 0644
